import requests
import pandas as pd

movies = [
    "The Shawshank Redemption",
    "The Godfather",
    "The Godfather Part II",
    "The Dark Knight",
    "Pulp Fiction",
    "Fight Club",
    "Forrest Gump",
    "Inception",
    "The Matrix",
    "Goodfellas",
    "Interstellar",
    "Parasite",
    "The Green Mile",
    "The Silence of the Lambs",
    "Saving Private Ryan",
    "City of God",
    "Se7en",
    "The Departed",
    "Whiplash",
    "Gladiator",
    "The Prestige",
    "Memento",
    "The Pianist",
    "American History X",
    "The Usual Suspects",
    "Léon",
    "The Intouchables",
    "The Lion King",
    "Terminator 2: Judgment Day",
    "Back to the Future",
    "The Lord of the Rings: The Fellowship of the Ring",
    "The Lord of the Rings: The Two Towers",
    "The Lord of the Rings: The Return of the King",
    "Star Wars",
    "The Empire Strikes Back",
    "Return of the Jedi",
    "Alien",
    "Aliens",
    "Blade Runner",
    "Blade Runner 2049",
    "Django Unchained",
    "Inglourious Basterds",
    "The Wolf of Wall Street",
    "Shutter Island",
    "Gone Girl",
    "The Social Network",
    "No Country for Old Men",
    "There Will Be Blood",
    "Prisoners",
    "Arrival",
    "Dune",
    "Dune: Part Two",
    "Oppenheimer",
    "The Truman Show",
    "Eternal Sunshine of the Spotless Mind",
    "Her",
    "Lost in Translation",
    "The Grand Budapest Hotel",
    "The Royal Tenenbaums",
    "Fantastic Mr. Fox",
    "Moonrise Kingdom",
    "The French Dispatch",
    "The Shining",
    "2001: A Space Odyssey",
    "A Clockwork Orange",
    "Full Metal Jacket",
    "Eyes Wide Shut",
    "Dr. Strangelove",
    "Apocalypse Now",
    "Taxi Driver",
    "Raging Bull",
    "The Irishman",
    "Casino",
    "The King of Comedy",
    "Heat",
    "Scarface",
    "Carlito's Way",
    "Once Upon a Time in America",
    "The Good, the Bad and the Ugly",
    "Once Upon a Time in the West",
    "Reservoir Dogs",
    "Kill Bill: Vol. 1",
    "Kill Bill: Vol. 2",
    "The Hateful Eight",
    "Once Upon a Time in Hollywood",
    "Jackie Brown",
    "The Thing",
    "They Live",
    "Escape from New York",
    "American Psycho",
    "Black Swan",
    "Requiem for a Dream",
    "The Wrestler",
    "Mother!",
    "The Whale",
    "The Lighthouse",
    "The Northman",
    "Ex Machina",
    "Uncut Gems",
    "Good Time",
    "Midsommar",
    "Hereditary",
    "The Babadook",
    "Get Out",
    "Us",
    "Nope",
    "A Quiet Place",
    "The Conjuring",
    "It",
    "It Chapter Two",
    "The Exorcist",
    "The Sixth Sense",
    "The Others",
    "The Ring",
    "Scream",
    "Halloween",
    "The Texas Chain Saw Massacre",
    "The Shining",
    "Psycho",
    "Vertigo",
    "Rear Window",
    "North by Northwest",
    "Dial M for Murder",
    "Citizen Kane",
    "Casablanca",
    "12 Angry Men",
    "One Flew Over the Cuckoo's Nest",
    "The Godfather Part III",
    "A Beautiful Mind",
    "Good Will Hunting",
    "Dead Poets Society",
    "The Pursuit of Happyness",
    "The Curious Case of Benjamin Button",
    "The Theory of Everything",
    "The Imitation Game",
    "The Pianist",
    "Schindler's List",
    "The Boy in the Striped Pajamas",
    "Life Is Beautiful",
    "The Lives of Others",
    "Amélie",
    "Cinema Paradiso",
    "La La Land",
    "The Departed",
    "Argo",
    "Spotlight",
    "Birdman",
    "The Revenant",
    "Ford v Ferrari",
    "Moneyball",
    "The Big Short",
    "The Founder",
    "Steve Jobs",
    "Catch Me If You Can",
    "The Terminal",
    "Minority Report",
    "War of the Worlds",
    "Jaws",
    "Jurassic Park",
    "The Lost World: Jurassic Park",
    "E.T. the Extra-Terrestrial",
    "Indiana Jones and the Raiders of the Lost Ark",
    "Indiana Jones and the Last Crusade",
    "Saving Private Ryan",
    "Catch Me If You Can",
    "The Fabelmans",
    "West Side Story",
    "Schindler's List",
    "A.I. Artificial Intelligence",
    "Minority Report",
    "Ready Player One",
    "The Martian",
    "Black Hawk Down",
    "Alien",
    "Prometheus",
    "Gravity",
    "Children of Men",
    "The Road",
    "12 Years a Slave",
    "Moonlight",
    "Manchester by the Sea",
    "Room",
    "The Florida Project",
    "The Father",
    "Aftersun",
    "Past Lives",
    "Portrait of a Lady on Fire",
    "Call Me by Your Name",
    "The Worst Person in the World",
    "Another Round",
    "The Hunt",
    "Druk",
    "A Separation",
    "The Salesman",
    "About Elly",
    "The Past",
    "Incendies",
    "Enemy",
    "Sicario",
    "Sicario: Day of the Soldado",
    "Blade Runner 2049",
    "Looper",
    "Source Code",
    "Edge of Tomorrow",
    "Oblivion",
    "District 9",
    "Elysium",
    "Snowpiercer",
    "Oldboy",
    "Memories of Murder",
    "The Handmaiden",
    "Decision to Leave",
    "Burning",
    "Train to Busan",
    "The Wailing",
    "I Saw the Devil",
    "A Tale of Two Sisters",
    "Mother",
    "The Chaser",
    "The Host",
    "Perfect Blue",
    "Paprika",
    "Akira",
    "Ghost in the Shell",
    "Spirited Away",
    "Princess Mononoke",
    "My Neighbor Totoro",
    "Howl's Moving Castle",
    "Grave of the Fireflies",
    "Your Name",
    "Weathering with You",
    "A Silent Voice",
    "Tokyo Godfathers",
    "The Wind Rises",
    "Nausicaä of the Valley of the Wind",
    "Castle in the Sky",
    "The Tale of the Princess Kaguya",
    "Rashomon",
    "Seven Samurai",
    "Ikiru",
    "Tokyo Story",
    "Yojimbo",
    "Ran",
    "Kagemusha",
    "Harakiri",
    "High and Low",
    "The Seventh Seal",
    "Persona",
    "Wild Strawberries",
    "The Virgin Spring",
    "8½",
    "La Dolce Vita",
    "Bicycle Thieves",
    "Umberto D.",
    "The 400 Blows",
    "Breathless",
    "Contempt",
    "The Intouchables",
    "A Prophet",
    "The Lives of Others",
    "Downfall",
    "Das Boot",
    "The Pianist",
    "Run Lola Run",
    "The White Ribbon",
    "The Hunt",
    "Another Round",
    "The Square",
    "Triangle of Sadness",
    "Force Majeure",
    "Dogtooth",
    "The Lobster",
    "The Killing of a Sacred Deer",
    "Poor Things",
    "The Favourite",
    "The Lobster",
    "The Killing of a Sacred Deer",
    "Dogville",
    "Melancholia",
    "Dancer in the Dark",
    "Breaking the Waves",
    "The Seventh Seal",
    "The Invisible Guest",
    "Marshland",
    "The Secret in Their Eyes",
    "Wild Tales",
    "Nine Queens",
    "The Motorcycle Diaries",
    "Talk to Her",
    "All About My Mother",
    "Volver",
    "Pan's Labyrinth",
    "The Devil's Backbone",
    "Roma",
    "Y Tu Mamá También",
    "Amores Perros",
    "The Shape of Water",
    "Birdman",
    "Babel",
    "21 Grams",
    "Biutiful",
    "The Skin I Live In",
    "The Platform",
    "Society of the Snow",
    "The Invisible Guest",
    "Timecrimes",
    "REC",
    "The Orphanage",
    "Let the Right One In",
    "The Girl with the Dragon Tattoo",
    "The Square",
    "Force Majeure",
    "A Man Called Ove",
    "The 100-Year-Old Man Who Climbed Out the Window and Disappeared",
    "Tinker Tailor Soldier Spy",
    "The Imitation Game",
    "The Theory of Everything",
    "The King's Speech",
    "Darkest Hour",
    "1917",
    "Dunkirk",
    "Fury",
    "Hacksaw Ridge",
    "Platoon",
    "Full Metal Jacket",
    "The Thin Red Line",
    "Letters from Iwo Jima",
    "Flags of Our Fathers",
    "All Quiet on the Western Front",
    "The Deer Hunter",
    "Paths of Glory",
    "Lawrence of Arabia",
    "The Bridge on the River Kwai",
    "Ben-Hur",
    "Spartacus",
    "Gladiator",
    "Troy",
    "Kingdom of Heaven",
    "300",
    "The Last Samurai",
    "Braveheart",
    "Apocalypto",
    "The Passion of the Christ",
    "Master and Commander",
    "The Revenant",
    "Cast Away",
    "The Terminal",
    "Captain Phillips",
    "Sully",
    "United 93",
    "Apollo 13",
    "First Man",
    "The Right Stuff",
    "Hidden Figures",
    "The Pursuit of Happyness",
    "The Shawshank Redemption",
    "The Green Mile",
    "The Elephant Man",
    "American Beauty",
    "The Sixth Sense",
    "The Butterfly Effect",
    "Donnie Darko",
    "The Machinist",
    "The Game",
    "The Curious Case of Benjamin Button",
    "The Place Beyond the Pines",
    "Drive",
    "Nightcrawler",
    "Nocturnal Animals",
    "Enemy",
    "Under the Silver Lake",
    "The Killing of a Sacred Deer",
    "The Favourite",
    "The Menu",
    "Ready or Not",
    "Knives Out",
    "Glass Onion",
    "The Nice Guys",
    "Kiss Kiss Bang Bang",
    "Snatch",
    "Lock, Stock and Two Smoking Barrels",
    "RocknRolla",
    "The Gentlemen",
    "Layer Cake",
    "Sherlock Holmes",
    "Sherlock Holmes: A Game of Shadows",
    "V for Vendetta",
    "Watchmen",
    "Sin City",
    "300",
    "The Dark Knight Rises",
    "Batman Begins",
    "Joker",
    "The Batman",
    "Logan",
    "Deadpool",
    "Deadpool 2",
    "X-Men: Days of Future Past",
    "X-Men: First Class",
    "Spider-Man",
    "Spider-Man 2",
    "Spider-Man: Into the Spider-Verse",
    "Spider-Man: Across the Spider-Verse",
    "Iron Man",
    "Captain America: The Winter Soldier",
    "Avengers: Infinity War",
    "Avengers: Endgame",
    "Guardians of the Galaxy",
    "Guardians of the Galaxy Vol. 2",
    "Thor: Ragnarok",
    "Doctor Strange",
    "Black Panther",
    "Logan",
    "Man of Steel",
    "Superman",
    "Wonder Woman",
    "Watchmen",
    "V for Vendetta",
    "The Matrix Reloaded",
    "The Matrix Revolutions",
    "Terminator",
    "Terminator 3: Rise of the Machines",
    "Predator",
    "RoboCop",
    "Total Recall",
    "Die Hard",
    "Die Hard with a Vengeance",
    "Lethal Weapon",
    "Mad Max 2",
    "Mad Max: Fury Road",
    "Furiosa: A Mad Max Saga",
    "The Road Warrior",
    "Casino Royale",
    "Skyfall",
    "No Time to Die",
    "Mission: Impossible",
    "Mission: Impossible - Fallout",
    "Top Gun",
    "Top Gun: Maverick",
    "The Bourne Identity",
    "The Bourne Ultimatum",
    "John Wick",
    "John Wick: Chapter 2",
    "John Wick: Chapter 3",
    "John Wick: Chapter 4",
    "Kill Bill: Vol. 1",
    "Kill Bill: Vol. 2",
    "The Equalizer",
    "Taken",
    "Nobody",
    "Baby Driver",
    "The Town",
    "Inside Man",
    "Collateral",
    "Training Day",
    "American Gangster",
    "L.A. Confidential",
    "Mystic River",
    "Gone Baby Gone",
    "Zodiac",
    "The Girl with the Dragon Tattoo",
    "The Curious Case of Benjamin Button",
    "The Assassination of Jesse James by the Coward Robert Ford",
    "The Place Beyond the Pines",
    "The Tree of Life",
    "The Thin Red Line",
    "The New World",
    "A Ghost Story",
    "First Reformed",
    "The Green Knight",
    "The Lighthouse",
    "The Witch",
    "The Northman",
    "The Black Phone",
    "Talk to Me",
    "Barbarian",
    "Pearl",
    "X",
    "It Follows",
    "The Autopsy of Jane Doe",
    "Sinister",
    "The Conjuring 2",
    "Insidious",
    "Insidious: Chapter 2",
    "The Invisible Man",
    "A Quiet Place Part II",
    "10 Cloverfield Lane",
    "Cloverfield",
    "Annihilation",
    "Arrival",
    "Contact",
    "Interstellar",
    "The Martian",
    "Ad Astra",
    "Sunshine",
    "Moon",
    "Coherence",
    "Predestination",
    "The Butterfly Effect",
    "Primer",
    "Timecrimes",
    "The Endless",
    "Upgrade",
    "Ex Machina",
    "Her",
    "The Creator",
    "District 9",
    "Eternal Sunshine of the Spotless Mind",
    "Being John Malkovich",
    "Adaptation.",
    "Synecdoche, New York",
    "The Lobster",
    "The Killing of a Sacred Deer",
    "Swiss Army Man",
    "Everything Everywhere All at Once",
    "The Banshees of Inisherin",
    "The Father",
    "The Whale",
    "Nomadland",
    "Three Billboards Outside Ebbing, Missouri",
    "The Holdovers",
    "The Worst Person in the World",
    "Aftersun",
    "Past Lives",
    "Sound of Metal",
    "Minari",
    "Lady Bird",
    "Little Women",
    "Marriage Story",
    "Blue Valentine",
    "The Place Beyond the Pines",
    "Manchester by the Sea",
    "Moonlight",
    "Call Me by Your Name",
    "Portrait of a Lady on Fire",
    "Before Sunrise",
    "Before Sunset",
    "Before Midnight",
    "500 Days of Summer",
    "About Time",
    "The Perks of Being a Wallflower",
    "The Spectacular Now",
    "Good Will Hunting",
    "Dead Poets Society",
    "The Breakfast Club",
    "Stand by Me",
    "The Goonies",
    "Ferris Bueller's Day Off",
    "American Graffiti",
    "The Graduate",
    "The Godfather",
    "The Godfather Part II",
    "Once Upon a Time in America",
    "The French Connection",
    "Serpico",
    "Dog Day Afternoon",
    "Mean Streets",
    "The Conversation",
    "Chinatown",
    "L.A. Confidential",
    "The Usual Suspects",
    "The Sixth Sense",
    "Unbreakable",
    "Split",
    "Glass",
    "Signs",
    "The Village",
    "Old",
    "The Visit",
    "Knives Out",
    "Prisoners",
    "Gone Girl",
    "Se7en",
    "Zodiac",
    "The Game",
    "Panic Room",
    "The Girl with the Dragon Tattoo",
    "The Social Network",
    "Fight Club",
    "The Curious Case of Benjamin Button",
    "Mank",
    "Gone Baby Gone",
    "Argo",
    "The Town",
    "Air",
    "The Accountant",
    "The Way Back",
    "Ford v Ferrari",
    "Rush",
    "Warrior",
    "Creed",
    "Rocky",
    "Rocky II",
    "Million Dollar Baby",
    "Gran Torino",
    "Mystic River",
    "Unforgiven",
    "The Outlaw Josey Wales",
    "A Fistful of Dollars",
    "For a Few Dollars More",
    "The Good, the Bad and the Ugly",
    "Once Upon a Time in the West",
    "Django Unchained",
    "The Hateful Eight",
    "Kill Bill: Vol. 1",
    "Pulp Fiction",
    "Reservoir Dogs",
    "Jackie Brown",
    "Inglourious Basterds",
    "Once Upon a Time in Hollywood",
    "Sherlock Holmes",
    "Sherlock Holmes: A Game of Shadows",
    "The Grand Budapest Hotel",
    "The Royal Tenenbaums",
    "Fantastic Mr. Fox",
    "Isle of Dogs",
    "Moonrise Kingdom",
    "The Darjeeling Limited",
    "Rushmore",
    "The Life Aquatic with Steve Zissou",
    "The French Dispatch",
    "Asteroid City",
    "The Menu",
    "Poor Things",
    "The Favourite",
    "The Lobster",
    "The Killing of a Sacred Deer",
    "Dogtooth",
    "The Square",
    "Triangle of Sadness",
    "Force Majeure",
    "Another Round",
    "The Hunt",
    "A Separation",
    "The Salesman",
    "Incendies",
    "The Secret in Their Eyes",
    "Wild Tales",
    "Pan's Labyrinth",
    "Roma",
    "Amores Perros",
    "Y Tu Mamá También",
    "Oldboy",
    "Memories of Murder",
    "The Handmaiden",
    "Burning",
    "Decision to Leave",
    "Train to Busan",
    "The Wailing",
    "Parasite",
    "Mother",
    "The Chaser",
    "The Host",
    "Spirited Away",
    "Princess Mononoke",
    "Your Name",
    "A Silent Voice",
    "Akira",
    "Perfect Blue",
    "Paprika",
    "Grave of the Fireflies",
    "Rashomon",
    "Seven Samurai",
    "Ikiru",
    "Tokyo Story",
    "Harakiri",
    "Ran",
    "Yojimbo",
    "High and Low"
]



movie_data=[]
api_key="b7f66d1"
url="http://www.omdbapi.com/"

for title in movies:
  params={
  'apikey':api_key,
  't':title
  }
  response=requests.get(url=url,params=params)
  data=response.json()
  print(data)
  if data["Response"]=="True":
    movie_data.append(data)
  else:
    print("Invalid")

df=pd.DataFrame(movie_data)
print(df.columns)
df=df[['Title','Released','Ratings','Runtime','imdbRating','Director']]
df.to_csv("omdb_movies.csv", index=False)






